version: '3'

services:

  quakejs:
   build:
    context: quakejs-docker
   container_name: quakejs 
   environment:
    - SERVER=fartgod.xyz #44.230.73.135
    - HTTP_PORT=80
   expose:
    - 80
    - 27960

  nginx: 
   image: nginx:latest
   container_name: nginx
   volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - /etc/letsencrypt/:/etc/letsencrypt/
   ports:
    - 80:80
    - 443:443


  ide:
   build:
    context: ide
   container_name: ide 
   volumes: 
    - ./nginx.conf:/usr/src/nginx.conf
    - ./nginx2.conf:/usr/src/nginx2.conf
   working_dir: /usr/src
   command: >
      sh -c "jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
   restart: always
   ports:
    - 8888:8888
