version: '3'

services:

  quakejs:
   build:
    context: quakejs-docker
   container_name: quakejs 
   environment:
    - SERVER=0.0.0.0
    - HTTP_PORT=8080
   ports:
    - '8080:80'
    - '27960:27960'

  nginx: 
   image: nginx:latest
   container_name: nginx
   volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
   ports:
    - 80:80
    - 443:443


  ide:
   build:
    context: ide
   container_name: ide 
   volumes: 
    - ./nginx.conf:/usr/src/nginx.conf
   working_dir: /usr/src
   command: >
      sh -c "jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
   restart: always
   ports:
    - 8888:8888